I
@C:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\About.aspx.csutf-8R
IC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\About.aspx.designer.csutf-8Z
QC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\AddPhoneNumber.aspx.csutf-8c
ZC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\AddPhoneNumber.aspx.designer.csutf-8S
JC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Confirm.aspx.csutf-8\
SC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Confirm.aspx.designer.csutf-8R
IC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Forgot.aspx.csutf-8[
RC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Forgot.aspx.designer.csutf-8S
JC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Lockout.aspx.csutf-8\
SC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Lockout.aspx.designer.csutf-8Q
HC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Login.aspx.csutf-8Z
QC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Login.aspx.designer.csutf-8R
IC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Manage.aspx.csutf-8[
RC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Manage.aspx.designer.csutf-8X
OC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\ManageLogins.aspx.csutf-8a
XC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\ManageLogins.aspx.designer.csutf-8Z
QC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\ManagePassword.aspx.csutf-8c
ZC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\ManagePassword.aspx.designer.csutf-8]
TC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\OpenAuthProviders.ascx.csutf-8f
]C:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\OpenAuthProviders.ascx.designer.csutf-8T
KC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Register.aspx.csutf-8]
TC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\Register.aspx.designer.csutf-8a
XC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\RegisterExternalLogin.aspx.csutf-8j
aC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\RegisterExternalLogin.aspx.designer.csutf-8Y
PC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\ResetPassword.aspx.csutf-8b
YC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\ResetPassword.aspx.designer.csutf-8e
\C:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\ResetPasswordConfirmation.aspx.csutf-8n
eC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\ResetPasswordConfirmation.aspx.designer.csutf-8i
`C:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\TwoFactorAuthenticationSignIn.aspx.csutf-8r
iC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\TwoFactorAuthenticationSignIn.aspx.designer.csutf-8]
TC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\VerifyPhoneNumber.aspx.csutf-8f
]C:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Account\VerifyPhoneNumber.aspx.designer.csutf-8U
LC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\App_Start\BundleConfig.csutf-8W
NC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\App_Start\IdentityConfig.csutf-8T
KC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\App_Start\RouteConfig.csutf-8U
LC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\App_Start\Startup.Auth.csutf-8K
BC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Contact.aspx.csutf-8T
KC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Contact.aspx.designer.csutf-8K
BC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Default.aspx.csutf-8T
KC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Default.aspx.designer.csutf-8J
AC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Global.asax.csutf-8T
KC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Models\IdentityModels.csutf-8V
MC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Properties\AssemblyInfo.csutf-8J
AC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Site.Master.csutf-8S
JC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Site.Master.designer.csutf-8Q
HC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Site.Mobile.Master.csutf-8Z
QC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Site.Mobile.Master.designer.csutf-8F
=C:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\Startup.csutf-8P
GC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\ViewSwitcher.ascx.csutf-8Y
PC:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\ViewSwitcher.ascx.designer.csutf-8„
{C:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8„
{C:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8„
{C:\Users\jemimal.j\Downloads\ssds\ssds\Crazy\Crazy\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8